<div data-role="content">
    <ul data-role="listview" data-inset="true" data-filter="false">
        <li><a href="#landtag_berichte_map" data-transition="slide">Trendprognose</a></li>
        <li><a href="#landtag_berichte_kita" data-transition="slide">KiTa Pl&auml;tze Bayern</a></li>
        <li><a href="#landtag_berichte_bezirke" data-transition="slide">Regierungsbezirke</a></li>
        <li><a href="#landtag_berichte_kantine" data-transition="slide">Schwarzes Brett</a></li>
        <!-- <li><a href="#landtag_berichte_security" data-transition="slide">&Uuml;berwachungskamera</a></li>
        <li><a href="#landtag_berichte_kantine" data-transition="slide">Kantinenspeiseplan</a></li> -->
    </ul>
</div>