<div data-role="content">
    <table class="float-right" style="width:290px; font-size:90%; background:#FAFAFA; border:1px solid #bbb; margin:0px 0px 1em 1em; border-collapse:collapse;" summary="Infobox">
        <tr>
            <td colspan="2">
                <table style="border:0px; border-collapse:collapse; width:100%;" class="nogrid">
                    <tr>
                        <td style="text-align:center;"><a href="/w/index.php?title=Datei:Mittelfranken_Wappen.svg&amp;filetimestamp=20070319222358" class="image" title="Wappen"><img alt="Wappen" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Mittelfranken_Wappen.svg/100px-Mittelfranken_Wappen.svg.png" width="100" height="113" /></a><br />
                            <small>Wappen</small></td>
                        <td style="text-align:center;"><a href="/w/index.php?title=Datei:Flag_of_Middle_Franconia.svg&amp;filetimestamp=20100519042328" class="image" title="Flagge"><img alt="Flagge" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_Middle_Franconia.svg/149px-Flag_of_Middle_Franconia.svg.png" width="149" height="100" class="thumbborder" /></a><br />
                            <small>Flagge</small></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px; border-top:solid 1px #bbb;"><a href="/wiki/Staat" title="Staat">Staat</a>:</td>
            <td style="border-left:0px; border-top:solid 1px #bbb;"><a href="/wiki/Deutschland" title="Deutschland">Deutschland</a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px; border-top:solid 0px #bbb;"><a href="/wiki/Land_(Deutschland)" title="Land (Deutschland)">Bundesland</a>:</td>
            <td style="border-left:0px; border-top:solid 0px #bbb;"><a href="/wiki/Bayern" title="Bayern">Bayern</a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Verwaltungssitz" title="Verwaltungssitz">Verwaltungssitz</a>:</td>
            <td><a href="/wiki/Ansbach" title="Ansbach">Ansbach</a></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Gr&ouml;&szlig;te St&auml;dte:</td>
            <td><small>1.</small> <a href="/wiki/N%C3%BCrnberg" title="N&uuml;rnberg">N&uuml;rnberg</a><br />
                <small>2.</small> <a href="/wiki/F%C3%BCrth" title="F&uuml;rth">F&uuml;rth</a><br />
                <small>3.</small> <a href="/wiki/Erlangen" title="Erlangen">Erlangen</a><br />
                <small>4.</small> <a href="/wiki/Ansbach" title="Ansbach">Ansbach</a></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Fl%C3%A4cheninhalt" title="Fl&auml;cheninhalt">Fl&auml;che</a>:</td>
            <td>7.244,85&#160;<a href="/wiki/Quadratmeter#Quadratkilometer" title="Quadratmeter">km<sup>2</sup></a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Einwohnerzahl" title="Einwohnerzahl">Einwohner</a>:</td>
            <td>1.712.405 <small><i>(31.12.2008)</i></small></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Bev%C3%B6lkerungsdichte" title="Bev&ouml;lkerungsdichte">Bev&ouml;lkerungsdichte</a>:</td>
            <td>236 Einwohner je km<sup>2</sup></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Bezirkstagspr&auml;sident:</td>
            <td><a href="/wiki/Richard_Bartsch" title="Richard Bartsch">Richard Bartsch</a> (<a href="/wiki/Christlich-Soziale_Union_in_Bayern" title="Christlich-Soziale Union in Bayern">CSU</a>)</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Regierungspr&auml;sident:</td>
            <td><a href="/wiki/Thomas_Bauer_(N%C3%BCrnberg)" title="Thomas Bauer (N&uuml;rnberg)">Thomas Bauer</a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Webpr%C3%A4senz" title="Webpr&auml;senz" class="mw-redirect">Webpr&auml;senz</a>:</td>
            <td>
                <div style="overflow: hidden;"><a rel="nofollow" class="external text" href="http://www.bezirk-mittelfranken.de/">Bezirk</a><br />
                    <a rel="nofollow" class="external text" href="http://www.regierung.mittelfranken.bayern.de/">Regierung</a></div>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center;padding:3.5px;border-top:solid 1px #bbb;"><a href="/w/index.php?title=Datei:Locator_map_RB_Mittelfranken_in_Bavaria.svg&amp;filetimestamp=20090325181119" class="image"><img alt="Locator map RB Mittelfranken in Bavaria.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Locator_map_RB_Mittelfranken_in_Bavaria.svg/150px-Locator_map_RB_Mittelfranken_in_Bavaria.svg.png" width="150" height="148" /></a> <a href="/w/index.php?title=Datei:Locator_map_Mittelfranken_in_Germany.svg&amp;filetimestamp=20090324174834" class="image"><img alt="Locator map Mittelfranken in Germany.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Locator_map_Mittelfranken_in_Germany.svg/125px-Locator_map_Mittelfranken_in_Germany.svg.png" width="125" height="148" /></a><br />
                <small>Lage in Bayern und Deutschland</small></td>
        </tr>
    </table>
</div>