<div data-role="content">
    <table class="float-right" style="width:290px; font-size:90%; background:#FAFAFA; border:1px solid #bbb; margin:0px 0px 1em 1em; border-collapse:collapse;" summary="Infobox">
        <tr>
            <td colspan="2">
                <table style="border:0px; border-collapse:collapse; width:100%;" class="nogrid">
                    <tr>
                        <td style="text-align:center;"><a href="/w/index.php?title=Datei:Wappen_Oberbayern.svg&amp;filetimestamp=20091224171233" class="image" title="Wappen"><img alt="Wappen" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Wappen_Oberbayern.svg/100px-Wappen_Oberbayern.svg.png" width="100" height="114" /></a><br />
                            <small>Wappen</small></td>
                        <td style="text-align:center;"><a href="/w/index.php?title=Datei:Flagge_Oberbayern.svg&amp;filetimestamp=20100110175445" class="image" title="Flagge"><img alt="Flagge" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flagge_Oberbayern.svg/149px-Flagge_Oberbayern.svg.png" width="149" height="99" class="thumbborder" /></a><br />
                            <small>Flagge</small></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px; border-top:solid 1px #bbb;"><a href="/wiki/Staat" title="Staat">Staat</a>:</td>
            <td style="border-left:0px; border-top:solid 1px #bbb;"><a href="/wiki/Deutschland" title="Deutschland">Deutschland</a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px; border-top:solid 0px #bbb;"><a href="/wiki/Land_(Deutschland)" title="Land (Deutschland)">Bundesland</a>:</td>
            <td style="border-left:0px; border-top:solid 0px #bbb;"><a href="/wiki/Bayern" title="Bayern">Bayern</a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Verwaltungssitz" title="Verwaltungssitz">Verwaltungssitz</a>:</td>
            <td><a href="/wiki/M%C3%BCnchen" title="München">M&uuml;nchen</a></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Gr&ouml;&szlig;te St&auml;dte:</td>
            <td><small>1.</small> <a href="/wiki/M%C3%BCnchen" title="München">M&uuml;nchen</a><br />
                <small>2.</small> <a href="/wiki/Ingolstadt" title="Ingolstadt">Ingolstadt</a><br />
                <small>3.</small> <a href="/wiki/Rosenheim" title="Rosenheim">Rosenheim</a><br />
                <small>4.</small> <a href="/wiki/Freising" title="Freising">Freising</a></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Fl%C3%A4cheninhalt" title="Flächeninhalt">Fl&auml;che</a>:</td>
            <td>17.529,63&#160;<a href="/wiki/Quadratmeter#Quadratkilometer" title="Quadratmeter">km<sup>2</sup></sup></a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Einwohnerzahl" title="Einwohnerzahl">Einwohner</a>:</td>
            <td>4.346.465 <small><i>(31.12.2009)</i></small></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Bev%C3%B6lkerungsdichte" title="Bevölkerungsdichte">Bev&ouml;lkerungsdichte</a>:</td>
            <td>248 Einwohner je km<sup>2</sup></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Bezirkstagspr&auml;sident:</td>
            <td>Josef Mederer (<a href="/wiki/Christlich-Soziale_Union_in_Bayern" title="Christlich-Soziale Union in Bayern">CSU</a>)</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Regierungspr&auml;sident:</td>
            <td>Christoph Hillenbrand</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Webpr%C3%A4senz" title="Webpräsenz" class="mw-redirect">Webpr&auml;senz</a>:</td>
            <td>
                <div style="overflow: hidden;"><a rel="nofollow" class="external text" href="http://www.bezirk-oberbayern.de/">Bezirk</a><br />
                    <a rel="nofollow" class="external text" href="http://www.regierung.oberbayern.bayern.de/">Regierung</a></div>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center;padding:3.5px;border-top:solid 1px #bbb;"><a href="/w/index.php?title=Datei:Locator_map_RB_Oberbayern_in_Bavaria.svg&amp;filetimestamp=20090325181224" class="image"><img alt="Locator map RB Oberbayern in Bavaria.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Locator_map_RB_Oberbayern_in_Bavaria.svg/150px-Locator_map_RB_Oberbayern_in_Bavaria.svg.png" width="150" height="148" /></a> <a href="/w/index.php?title=Datei:Locator_map_Oberbayern_in_Germany.svg&amp;filetimestamp=20090324182227" class="image"><img alt="Locator map Oberbayern in Germany.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Locator_map_Oberbayern_in_Germany.svg/125px-Locator_map_Oberbayern_in_Germany.svg.png" width="125" height="148" /></a><br />
                <small>Lage in Bayern und Deutschland</small></td>
        </tr>
    </table>
</div>