<div data-role="content">
    <table class="float-right" style="width:290px; font-size:90%; background:#FAFAFA; border:1px solid #bbb; margin:0px 0px 1em 1em; border-collapse:collapse;" summary="Infobox">
        <tr>
            <td colspan="2">
                <table style="border:0px; border-collapse:collapse; width:100%;" class="nogrid">
                    <tr>
                        <td style="text-align:center;"><a href="/w/index.php?title=Datei:Wappen_Operpfalz.svg&amp;filetimestamp=20100914125801" class="image" title="Wappen"><img alt="Wappen" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Wappen_Operpfalz.svg/100px-Wappen_Operpfalz.svg.png" width="100" height="106" /></a><br />
                            <small>Wappen</small></td>
                        <td style="text-align:center;"><a href="/w/index.php?title=Datei:Flagge_Oberpfalz.svg&amp;filetimestamp=20100915131847" class="image" title="Flagge"><img alt="Flagge" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flagge_Oberpfalz.svg/149px-Flagge_Oberpfalz.svg.png" width="149" height="89" class="thumbborder" /></a><br />
                            <small>Flagge</small></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px; border-top:solid 1px #bbb;"><a href="/wiki/Staat" title="Staat">Staat</a>:</td>
            <td style="border-left:0px; border-top:solid 1px #bbb;"><a href="/wiki/Deutschland" title="Deutschland">Deutschland</a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px; border-top:solid 0px #bbb;"><a href="/wiki/Land_(Deutschland)" title="Land (Deutschland)">Bundesland</a>:</td>
            <td style="border-left:0px; border-top:solid 0px #bbb;"><a href="/wiki/Bayern" title="Bayern">Bayern</a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Verwaltungssitz" title="Verwaltungssitz">Verwaltungssitz</a>:</td>
            <td><a href="/wiki/Regensburg" title="Regensburg">Regensburg</a></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Gr&ouml;&szlig;te St&auml;dte:</td>
            <td><small>1.</small> <a href="/wiki/Regensburg" title="Regensburg">Regensburg</a><br />
                <small>2.</small> <a href="/wiki/Amberg" title="Amberg">Amberg</a><br />
                <small>3.</small> <a href="/wiki/Weiden_in_der_Oberpfalz" title="Weiden in der Oberpfalz">Weiden</a><br />
                <small>4.</small> <a href="/wiki/Neumarkt_in_der_Oberpfalz" title="Neumarkt in der Oberpfalz">Neumarkt</a></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Fl%C3%A4cheninhalt" title="Fl&auml;cheninhalt">Fl&auml;che</a>:</td>
            <td>9.691,03&#160;<a href="/wiki/Quadratmeter#Quadratkilometer" title="Quadratmeter">km<sup>2</sup></a></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Einwohnerzahl" title="Einwohnerzahl">Einwohner</a>:</td>
            <td>1.081.417 <small><i>(31.&#160;Dez.&#160;2009)</i></small></td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Bev%C3%B6lkerungsdichte" title="Bev&ouml;lkerungsdichte">Bev&ouml;lkerungsdichte</a>:</td>
            <td>112 Einwohner je km<sup>2</sup></td>
        </tr>
        <tr>
            <td colspan="2" style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;">&#160;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Bezirkstagspr&auml;sident:</td>
            <td><a href="/wiki/Franz_L%C3%B6ffler" title="Franz L&ouml;ffler">Franz L&ouml;ffler</a> (<a href="/wiki/Christlich-Soziale_Union_in_Bayern" title="Christlich-Soziale Union in Bayern">CSU</a>)</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Regierungspr&auml;sidentin:</td>
            <td>Brigitta Brunner</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;"><a href="/wiki/Webpr%C3%A4senz" title="Webpr&auml;senz" class="mw-redirect">Webpr&auml;senz</a>:</td>
            <td>
                <div style="overflow: hidden;"><a rel="nofollow" class="external text" href="http://www.bezirk-oberpfalz.de/">Bezirk</a><br />
                    <a rel="nofollow" class="external text" href="http://www.regierung.oberpfalz.bayern.de/">Regierung</a></div>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center;padding:3.5px;border-top:solid 1px #bbb;"><a href="/w/index.php?title=Datei:Locator_map_RB_Oberpfalz_in_Bavaria.svg&amp;filetimestamp=20090325181513" class="image"><img alt="Locator map RB Oberpfalz in Bavaria.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Locator_map_RB_Oberpfalz_in_Bavaria.svg/150px-Locator_map_RB_Oberpfalz_in_Bavaria.svg.png" width="150" height="148" /></a> <a href="/w/index.php?title=Datei:Locator_map_Oberpfalz_in_Germany.svg&amp;filetimestamp=20090324182312" class="image"><img alt="Locator map Oberpfalz in Germany.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Locator_map_Oberpfalz_in_Germany.svg/125px-Locator_map_Oberpfalz_in_Germany.svg.png" width="125" height="148" /></a><br />
                <small>Lage in Bayern und Deutschland</small></td>
        </tr>
    </table>
</div>