<div data-role="content">
    <table class="float-right" summary="Infobox" style="width:290px; font-size:90%; background:#FAFAFA; border:1px solid #bbb; margin:0px 0px 1em 1em; border-collapse:collapse;">
        <tbody>
        <tr>
            <td colspan="2">
                <table class="nogrid" style="border:0px; border-collapse:collapse; width:100%;">
                    <tbody>
                    <tr>
                        <td style="text-align:center;">
                            <a class="image" title="Wappen" href="/w/index.php?title=Datei:Unterfranken_Wappen.svg&filetimestamp=20100914131957">
                                <img width="100" height="111" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Unterfranken_Wappen.svg/100px-Unterfranken_Wappen.svg.png" alt="Wappen">
                            </a>
                            <br>
                            <small>Wappen</small>
                        </td>
                        <td style="text-align:center;">
                            <a class="image" title="Flagge" href="/w/index.php?title=Datei:Flag_of_Lower_Franconia.svg&filetimestamp=20100914132538">
                                <img class="thumbborder" width="149" height="94" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Lower_Franconia.svg/149px-Flag_of_Lower_Franconia.svg.png" alt="Flagge">
                            </a>
                            <br>
                            <small>Flagge</small>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px; border-top:solid 1px #bbb;">
                <a title="Staat" href="/wiki/Staat">Staat</a>
                :
            </td>
            <td style="border-left:0px; border-top:solid 1px #bbb;">
                <a title="Deutschland" href="/wiki/Deutschland">Deutschland</a>
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px; border-top:solid 0px #bbb;">
                <a title="Land (Deutschland)" href="/wiki/Land_(Deutschland)">Bundesland</a>
                :
            </td>
            <td style="border-left:0px; border-top:solid 0px #bbb;">
                <a title="Bayern" href="/wiki/Bayern">Bayern</a>
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">
                <a title="Verwaltungssitz" href="/wiki/Verwaltungssitz">Verwaltungssitz</a>
                :
            </td>
            <td>
                <a title="Würzburg" href="/wiki/W%C3%BCrzburg">W&uuml;rzburg</a>
            </td>
        </tr>
        <tr>
            <td style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;" colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Gr&ouml;&szlig;te St&auml;dte:</td>
            <td>
                <small>1.</small>
                <a title="Würzburg" href="/wiki/W%C3%BCrzburg">W&uuml;rzburg</a>
                <br>
                <small>2.</small>
                <a title="Aschaffenburg" href="/wiki/Aschaffenburg">Aschaffenburg</a>
                <br>
                <small>3.</small>
                <a title="Schweinfurt" href="/wiki/Schweinfurt">Schweinfurt</a>
                <br>
                <small>4.</small>
                <a title="Bad Kissingen" href="/wiki/Bad_Kissingen">Bad Kissingen</a>
            </td>
        </tr>
        <tr>
            <td style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;" colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">
                <a title="Flächeninhalt" href="/wiki/Fl%C3%A4cheninhalt">Fl&auml;che</a>
                :
            </td>
            <td>
                8.530,99&nbsp;
                <a title="Quadratmeter" href="/wiki/Quadratmeter#Quadratkilometer">km<sup>2</sup></a>
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">
                <a title="Einwohnerzahl" href="/wiki/Einwohnerzahl">Einwohner</a>
                :
            </td>
            <td>
                1.327.497
                <small>
                    <i>(31.12.2008)</i>
                </small>
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">
                <a title="Bevölkerungsdichte" href="/wiki/Bev%C3%B6lkerungsdichte">Bev&ouml;lkerungsdichte</a>
                :
            </td>
            <td>156 Einwohner je km<sup>2</sup></td>
        </tr>
        <tr>
            <td style="padding:0px; font-size:1px; line-height:1px; border-bottom:solid 1px #bbb;" colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Bezirkstagspr&auml;sident:</td>
            <td>
                <a title="Erwin Dotzel" href="/wiki/Erwin_Dotzel">Erwin Dotzel</a>
                (
                <a title="Christlich-Soziale Union in Bayern" href="/wiki/Christlich-Soziale_Union_in_Bayern">CSU</a>
                )
            </td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">Regierungspr&auml;sident:</td>
            <td>Paul Beinhofer</td>
        </tr>
        <tr>
            <td style="font-weight:bold; padding-left:8px;">
                <a class="mw-redirect" title="Webpräsenz" href="/wiki/Webpr%C3%A4senz">Webpr&auml;senz</a>
                :
            </td>
            <td>
                <div style="overflow: hidden;">
                    <a class="external text" href="http://www.bezirk-unterfranken.de/" rel="nofollow">Bezirk</a>
                    <br>
                    <a class="external text" href="http://www.regierung.unterfranken.bayern.de/" rel="nofollow">Regierung</a>
                </div>
            </td>
        </tr>
        <tr>
            <td style="text-align:center;padding:3.5px;border-top:solid 1px #bbb;" colspan="2">
                <a class="image" href="/w/index.php?title=Datei:Locator_map_RB_Unterfranken_in_Bavaria.svg&filetimestamp=20090325181622">
                    <img width="150" height="148" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Locator_map_RB_Unterfranken_in_Bavaria.svg/150px-Locator_map_RB_Unterfranken_in_Bavaria.svg.png" alt="Locator map RB Unterfranken in Bavaria.svg">
                </a>
                <a class="image" href="/w/index.php?title=Datei:Locator_map_Unterfranken_in_Germany.svg&filetimestamp=20090324185415">
                    <img width="125" height="148" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Locator_map_Unterfranken_in_Germany.svg/125px-Locator_map_Unterfranken_in_Germany.svg.png" alt="Locator map Unterfranken in Germany.svg">
                </a>
                <br>
                <small>Lage in Bayern und Deutschland</small>
            </td>
        </tr>
        </tbody>
    </table>
</div>