<div data-role="content">
    <table>
        <tr>
            <td>Raucherschutzgesetz</td>
            <td><img src="imgs/map/go_medium_down.png"></td>
        </tr>
        <tr>
            <td>Datenschutz</td>
            <td><img src="imgs/map/go_up.png"></td>
        </tr>
        <tr>
            <td>Autobahnmaut</td>
            <td><img src="imgs/map/go_medium_down.png"></td>
        </tr>
        <tr>
            <td>Finanzpolitik</td>
            <td><img src="imgs/map/go_medium.png"></td>
        </tr>
        <tr>
            <td>Umweltpolitik</td>
            <td><img src="imgs/map/go_up_medium.png"></td>
        </tr>
    </table>
</div>