<div data-role="content">
    <ul data-role="listview" data-inset="true" data-filter="false">
        <li><a href="#landtag_berichte_bezirke_mittelfranken" data-transition="slide">Mittelfranken</a></li>
        <li><a href="#landtag_berichte_bezirke_niederbayern" data-transition="slide">Niederbayern</a></li>
        <li><a href="#landtag_berichte_bezirke_oberbayern" data-transition="slide">Oberbayern</a></li>
        <li><a href="#landtag_berichte_bezirke_oberfranken" data-transition="slide">Oberfranken</a></li>
        <li><a href="#landtag_berichte_bezirke_oberpfalz" data-transition="slide">Oberpfalz</a></li>
        <li><a href="#landtag_berichte_bezirke_schwaben" data-transition="slide">Schwaben</a></li>
        <li><a href="#landtag_berichte_bezirke_unterfranken" data-transition="slide">Unterfranken</a></li>
    </ul>
</div>